<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SqlFlowSdk.Monitoring\SqlFlowSdk.Monitoring.csproj" />
	</ItemGroup>
</Project>
